version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mudanca_facil
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
